### ISSUE TITLE
Enable `esModuleInterop` by default in TS configs

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/javascript#15]
"Is there a good reason not to use esModuleInterop in TypeScript?"

In @dagda1 we trust 

![I would set it in your base tsconfig
I always set it
I think import * was the original intention but after babel, it never really caught on
I find import * as a default import confusing](https://user-images.githubusercontent.com/4205/91490799-a4fd3a80-e878-11ea-8253-76287d002595.png)

**Comment by dagda1** [comment]
could we do this in the `@frontside/tsconfig` or is that too big a breaking change.

If not we could have a base `@bigtest/config` that extends `@frontside/tsconfig`

**Comment by cowboyd** [comment]
@dagda1 I think we should do this in `@frontside/tsconfig`

**Comment by dagda1** [comment]
I've created #16 for this

**Comment by cowboyd** [comment]
Closed by #16
